language: go
sudo: false
go:
- '1.8'
install: true
script:
- GOOS=linux GOARCH=amd64 go build -o bin/protoc-gen-js-fetch-linux-amd64 -ldflags "-w" github.com/sercand/grpc-js-fetch/protoc-gen-js-fetch
- GOOS=darwin GOARCH=amd64 go build -o bin/protoc-gen-js-fetch-darwin-amd64 -ldflags "-w" github.com/sercand/grpc-js-fetch/protoc-gen-js-fetch
deploy:
  provider: releases
  file:
  - bin/protoc-gen-js-fetch-linux-amd64
  - bin/protoc-gen-js-fetch-darwin-amd64
  skip_cleanup: true
  on:
    repo: sercand/grpc-js-fetch
    tags: true
  api_key:
    secure: e5fyzsahbvr/B6CAAIovcOcuRvMWwSmjHylBwIuCSFZr3Lu+e0i/8X049mpBP7SgOPd9YON/pr73Y3Qg7s8WB55uIi+WWVMw7DwNFG/dAdaUt2kVWn7ALYDoEs+VeFfQDn5gcLBgIQAJDkiF8SD35RLTGm6WlMNvyCDXoidK+q6l1t9+V7YZ6OBgWChZg0XyZrgOzmPJ0yZEQCj10pXOG0fl5EhUQAzkNPiGcP4MorT1TZuadkzkRFhQ0SxXybVqeRlsZPQod2NXkxW5hT/qI0wdYu874eoSkGPY/QQyHF72WK86M5EK/IBxtnV1CdK+bDoQCqYusU/dLyX0V83LJ/HTcVwt32GhO7vSj7hJXYtk0PkgvujFIdWha68KCqRig/NDrgzM+x5GMOACoHGTg0XsA+7s+7VnQDksA0toQpsXaW/BzfoKujbh+QIBXM39Hjfx1tCBemB1aJfIlMhlN1CkPSBuCBeEyzxzNtedGO6pX3nfw9QIPP7qVXtPLO70a0QTNYB5PI6L7dMhwMKt76ABHcyPbE/OzToLAajg24zZ4QFmW5NYCEYuHI61DPbQdp6lUIip9FD4kJ6M7NBNK3Z5LfVupr21ATisYcSlBeAIKc5JyvFOxMzdmiMS0UzKic1vQJJAzU8KoyMOBu8NTABvse7m3lO26CjfNaeWuZU=
notifications:
  email: false
